market:
	env GOOS=linux GOARCH=arm64 go build market.go
launcher:
	env GOOS=linux GOARCH=arm64 go build launcher.go
match:
	env GOOS=linux GOARCH=arm64 go build match.go
multimatch:
	env GOOS=linux GOARCH=arm64 go build multimatch.go
